name: BUILD

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [aarch64, aarch64-musl, amd64, amd64-musl]
        include:
          - build: aarch64 
            os: ubuntu-latest
            rust: stable
            cross: true
            target: aarch64-unknown-linux-gnu
          - build: aarch64-musl
            os: ubuntu-latest
            rust: stable
            cross: true
            target: aarch64-unknown-linux-musl
          - build: amd64 
            os: ubuntu-latest
            rust: stable
            cross: false
            target: x86_64-unknown-linux-gnu
          - build: amd64-musl
            os: ubuntu-latest
            rust: stable
            cross: true
            target: x86_64-unknown-linux-musl
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.cross }}
        command: build
        args: --release --target ${{ matrix.target }}
    - run: mv ./target/release/archlinux-repo ./archlinux-repo-${{ matrix.build }} || mv "./target/${{ matrix.target }}/release/archlinux-repo" ./archlinux-repo-${{ matrix.build }}

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "release"
        artifacts: "./archlinux-repo-${{ matrix.build }}"
        token: ${{ secrets.GITHUB_TOKEN }}
